[workspace]
members = [
  "programs/zk_location_verifier",
  "programs/hyperlocal_markets",
]

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[toolchain]
anchor_version = "0.31.1"

[programs.localnet]
zk_location_verifier = "Hr7Wh6PHTsS7e74HQWtafBjNhj9egXQgAM9yeWSnwsDD"
hyperlocal_markets = "8pkLV5wpiXFTu9VGwhDMdUESp1RkQUPfa8CyqT2bKket"


[programs.devnet]
zk_location_verifier = "56qEvUYQnhfEf557ftLVdjtwqfJA6TpG2cnru3MyhT7Z"
hyperlocal_markets = "EA838rrQJPTmk4FNMRV4esgU7rFo5oRLGgW1Nws1jzox"

[scripts]

[test.validator]
rpc_port = 8899
ledger = ".anchor/test-ledger"
bind_address = "127.0.0.1"
startup_wait = 10000
