[workspace]
members = [
  "programs/zk_location_verifier",
  "programs/hyperlocal_markets",
]

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[toolchain]
anchor-lang = "0.31.1"
proc-macro2 = "1.0.94"

[programs.localnet]
zk_location_verifier = "Hr7Wh6PHTsS7e74HQWtafBjNhj9egXQgAM9yeWSnwsDD"
hyperlocal_markets = "8pkLV5wpiXFTu9VGwhDMdUESp1RkQUPfa8CyqT2bKket"

[scripts]
test = "anchor test"
